Guideline Level

<center><p style="font-size:50px; font-weight:bold">
Python Accessing the data
</p></center>

Data Types, Data Structures, Class

In [ ]:
# Packages
import numpy as np
import matplotlib.pylab as plt

# Inspect your data

In [ ]:
# Check the data type
var = "test"
class_var = type(var)

# Check the data dimensions and length
length_var = len(var)

# print the result
print(class_var, length_var)

# Data Types
**Cc**
1. Object: All things in the Python environment could be seen as an object
2. Variable:

## Numeric data (Integer, Float, Double and Complex (imaginary numbers))

In [3]:
# Integer
var_int = 1.21
trans_int = int(var_int)

# Float / Double
var_dec = 1.2
trans_dec = float(trans_int)

# Complex

# print the result
print(trans_int, trans_dec)

1 1.0


## Character data / String

In [1]:
# String
str = 'sdf'

# Link Strings
lk_str = str+' '+str

# print the result
print(lk_str)

sdf sdf


## Logical data

## Raw (bytes).


# Data Structure

## Array (Vector, Matrix, Array)

In [16]:
# Variables
vector = np.array([1,2,3,4])
matrix = np.array([[1,2,3,4], [2,4,5,6]])
array = np.array([[1,2,3,4], [2,4,5,6], [2,4,5,6]])

# Matrix Calculation
print(matrix+matrix)
print(matrix*2)
print(array*vector) # Tips: it is not the matrix multiplication
print(np.matmul(array, np.matrix.transpose(matrix)) # Matrix multiplication



[[ 2  4  6  8]
 [ 4  8 10 12]]
[[ 2  4  6  8]
 [ 4  8 10 12]]
[[ 1  4  9 16]
 [ 2  8 15 24]
 [ 2  8 15 24]]
[[30 49]
 [49 81]
 [49 81]]
